### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by 9ao9ai9ar**
See commit messages.

### CODE REVIEW

**Comment by beucismis** [comment]
Thanks for contribute.

**Comment by beucismis** [comment]
But, this branch has conflicts that must be resolved...
https://github.com/beucismis/awesome-fetch/pull/77/conflicts

**Comment by 9ao9ai9ar** [comment]
Fixed. Please check again, thanks.

**Comment by beucismis** [comment]
Thanks.

**Pull request merged**
