### PR TITLE
Add ufetch

### PR DESCRIPTION
**Pull request by grahamperrin**
Thanks to /u/two-horned at <https://old.reddit.com/r/freebsd/comments/tyrf9q/-/i6ju7m7/?context=1> for the hint.

### CODE REVIEW

**Comment by grahamperrin** [comment]
Do you mean, remove the anchor from the link? 

The developer's own description is "Tiny system info for Unix-like operating systems.".

For one of the files, <https://gitlab.com/jschx/ufetch/-/blob/master/ufetch-freebsd#L1> I see `#!/bin/sh`, I'll assume shell for all.

**Comment by beucismis** [comment]
I mean put a period at the end of the description and then indicate which language it is written in.

**Comment by wick3dr0se** [comment]
@beucismis why do you refuse to edit PR's yourself? You'd just rather nitpick at a grammar or punctuation issue than taking 5 seconds to fix it?

**Comment by beucismis** [comment]
PR: [d2b939c](https://github.com/beucismis/awesome-fetch/commit/d2b939c3dd662b9dfa0ba1bd9b90953060744c47)

**Pull request closed without merging**
